### ISSUE TITLE
SLD radioactive source custodian

### ISSUE THREAD

**Issue by akerib** [FPD-Management/Actions#13]
Email from Nimmi - the rad sources in SLD were under Sandy's custodianship and need to be transferred to a new custodian. That person needs to have RWT-I (ESH 116) training. A list of the sources is appended. I've asked her for a list of RWT-I's in FPD. 

RECORD NUMBER | Place Holder | TYPE | Radionuclide | SERIAL # | SERIAL # | DATE MOVED | FACILITY | LOCATION BLDG/AREA | SUB LOCATION | CUSTODIAN/ CUSTODIAN GROUP
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SERIAL #
21 | NO | SS | Am-241 | 36009-1 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | SANDY PIERSON
22 | NO | SS | Am-241 | 36009-2 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | SANDY PIERSON
23 | NO | SS | Am-241 | 36009-3 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | SANDY PIERSON
24 | NO | SS | Am-241 | 36009-4 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | SANDY PIERSON
25 | NO | SS | Am-241 | 36009-5 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | PIERSON
26 | NO | SS | Am-241 | 36009-6 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | SANDY PIERSON
27 | NO | SS | Am-241 | 36009-7 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | SANDY PIERSON
28 | NO | SS | Am-241 | 36009-8 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | SANDY PIERSON
29 | NO | SS | Am-241 | 36009-9 | 4/20/2011 | LINAC | 750 | CEH DETECTOR | PIERSON
  |   |   |   |   |   |   |   |   |

**Comment by akerib** [comment]
Attached is a list of all FPDers with 116 training. Who's the youngest person on the list that worked on SLD?!?! 

[FPD 116 training.docx](https://github.com/FPD-Management/Actions/files/1925547/FPD.116.training.docx)

**Comment by richardxdubois** [comment]
Dan will ask Peter Rowson if he can be custodian

**Comment by akerib** [comment]
Peter has agreed... asked Nimmi to followup with him and RP.
