### ISSUE TITLE
Ask Julie McEnery to attend HEPAP to support FGST

### ISSUE THREAD

**Issue by richardxdubois** [FPD-Management/Actions#22]
On May 14-15.

**Comment by richardxdubois** [comment]
Julie has agreed (I told her the dates):

> Hi Richard,
>
>I’d be happy to do this, just let me know when and where (and what I can do to help with preparations etc for the meeting).
>
>Julie

**Comment by richardxdubois** [comment]
@joahewett - do you have logistics yet to pass on to her? Any particular session, day... and she should just turn up? No prep?

**Comment by joahewett** [comment]
Afternoon on Monday May 14.  See:  https://science.energy.gov/hep/hepap/meetings/  for coordinates.  An agenda should be posted soon.

**Comment by richardxdubois** [comment]
I've transmitted the logistics to Julie. Closing the issue.
