### ISSUE TITLE
Nature Publication and Stanford Open Access query from ATLAS

### ISSUE THREAD

**Issue by richardxdubois** [FPD-Management/Actions#26]
From the ATLAS folks. I've asked Peter Michelson, for his Fermi experience.

H iMichael,
 
Short answer is I am not sure. Google found many links, by individual schools or departments, discussions of plans etc, but I don’t see a Stanford-wide policy. Similar situation at SLAC. Best to ask JoAnne. Maybe Richard Dubois, who is her Deputy and is cc’ed here, can answer. Cheers.
 
Charlie
--
Charles C. Young
M.S. 43, SLAC National Accelerator Laboratory       
P.O. Box 20450                                        
Stanford, CA 94309                                      
young@slac.stanford.edu                                
voice  (650) 926 2669                        
fax    (650) 926 2923                      
CERN GSM +41 75 411 2069
From: Michael Kagan <makagan@slac.stanford.edu>
Date: Monday, May 14, 2018 at 01:39
To: "Young, Charles C." <young@slac.stanford.edu>, Dong Su <sudong@slac.stanford.edu>, Ariel Schwartzman <sch@slac.stanford.edu>
Subject: Nature publication and SLAC / Stanford Open Access Policy
 
Hi Charlie, Su Dong, Ariel,
 
The review of ML in HEP for Nature I worked on with a few other physicists has been accepted!  Before publication, pne thing that came up is that we need to sign a waiver about Open Access Policy for publication if our institute has one.
 
Do you know if SLAC / Stanford has one? Or do you know who I could contact about it?
 
Best,
Michael

**Comment by richardxdubois** [comment]
Response from Peter:

Good question.  To my knowledge Stanford does not have an Open Access requirement (i.e. a publication must be open and freely accessible to anyone.).  Apparently, since 2013, UC has had an Open Access Policy.  There is discussion at the following Stanford libraries website that maybe useful:

https://library.stanford.edu/using/copyright-reminder/common-situations/publishing

Peter

**Comment by joahewett** [comment]
I don’t think we have such a policy.  A good place to check might actually be communications, since they know of other papers that have been accepted to Nature and then we can ask them how they handled this.

Communications should know about this anyway, so they can communicate it!  Melinda Lee is the contact.

-JoA

**Comment by May152018** [comment]
Please check with Maggie Lorea: https://www-public.slac.stanford.edu/phonebook/dirsearch.aspx?emplid=384992&ntype=1

-----Original Message-----

**Comment by richardxdubois** [comment]
Closing the loop, and the issues from Melissa:

Hi Michael,
 
No open access policy at SLAC, just the requirement for DOE-funded authors to report their publication to OSTI. Maggie Loera (maggiel@slac.stanford.edu) here at the lab can give you more details on that front if you need it.
 
Hope this helps, and look forward to speaking soon. J
 
Best,
M
